# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-27 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='image',
        ),
    ]
