# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-28 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_mobile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='codechef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
    ]
