# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-28 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_codechef'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='codechef',
            new_name='chef',
        ),
    ]
