# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-31 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='chefuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('currentrating', models.TextField()),
                ('highestrating', models.TextField()),
            ],
        ),
    ]
